packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@types/node': 20.19.43
  tsdown: 0.22.3
  typescript: 6.0.3
  vitest: 4.1.9
linkWorkspacePackages: true
preferWorkspacePackages: true
allowBuilds:
  '@swc/core': true
  core-js: true
  es5-ext: true
  esbuild: true
  sqlite3: true
minimumReleaseAgeExclude:
  - '@w5s/tsdown-config@1.0.0-alpha.6'
