packages:
  - 'apps/*'
  - 'packages/*'
linkWorkspacePackages: true
preferWorkspacePackages: true
allowBuilds:
  '@swc/core': true
  core-js: true
  es5-ext: true
  esbuild: true
  sqlite3: true
minimumReleaseAgeExclude:
  - '@w5s/tsdown-config@1.0.0-alpha.6'
