import { describe, expect, it } from 'vitest';
import { RequestDestination } from './RequestDestination.js';

describe('RequestDestination', () => {
  it('is an enum', () => {
    expect(RequestDestination).toMatchInlineSnapshot(`
      {
        "Audio": "audio",
        "AudioWorklet": "audioworklet",
        "Document": "document",
        "Embed": "embed",
        "Empty": "",
        "Font": "font",
        "Frame": "frame",
        "Iframe": "iframe",
        "Image": "image",
        "Manifest": "manifest",
        "Object": "object",
        "PaintWorklet": "paintworklet",
        "Report": "report",
        "Script": "script",
        "SharedWorker": "sharedworker",
        "Style": "style",
        "Track": "track",
        "Video": "video",
        "Worker": "worker",
        "XSLT": "xslt",
        "codecDecode": [Function],
        "codecEncode": [Function],
        "codecSchema": [Function],
        "from": [Function],
        "hasInstance": [Function],
        "inspect": undefined,
        "typeName": "Enum",
        Symbol(w5s.enumKeys): [
          "Empty",
          "Audio",
          "AudioWorklet",
          "Document",
          "Embed",
          "Font",
          "Frame",
          "Iframe",
          "Image",
          "Manifest",
          "Object",
          "PaintWorklet",
          "Report",
          "Script",
          "SharedWorker",
          "Style",
          "Track",
          "Video",
          "Worker",
          "XSLT",
        ],
        Symbol(w5s.enumValues): [
          "",
          "audio",
          "audioworklet",
          "document",
          "embed",
          "font",
          "frame",
          "iframe",
          "image",
          "manifest",
          "object",
          "paintworklet",
          "report",
          "script",
          "sharedworker",
          "style",
          "track",
          "video",
          "worker",
          "xslt",
        ],
      }
    `);
  });
});
